## Docker image to run gdp-server

# Based on ubuntu
FROM ubuntu:14.04

MAINTAINER Nitesh Mor <mor@eecs.berkeley.edu>

# stop stupid debconf errors
ENV DEBIAN_FRONTEND noninteractive

# Update package list
RUN apt-get update

# fetch debian package
ADD gdp-server*.deb /

# install debian package, this will fail -- we will fix that in next step
RUN dpkg -i /gdp-server*.deb || true

# fix the dependencies
RUN apt-get -f install -y || true

# Make sure we can overwrite /etc/ep_adm_params/gdplogd as user gdp later on
RUN chmod -R a+w /etc/ep_adm_params

# This uses /bin/sh's echo, that doesn't take '-e' and interprets backlash by default
RUN echo '#!/bin/bash\necho "Replacing gdpname with $1"\n/bin/sed -i "s/swarm.gdplogd.gdpname=.*/swarm.gdplogd.gdpname=$1/g" /etc/ep_adm_params/gdplogd\necho "swarm.gdp.zeroconf.enable = false" >> /etc/ep_adm_params/gdplogd\n/bin/sleep 10\n/usr/bin/gdplogd ${*:2}' > /wrapper.sh && chmod a+x /wrapper.sh

USER gdp

# The first argument is the logd's name. Be careful
ENTRYPOINT ["/bin/bash", "/wrapper.sh"]
