## Docker image to run gdp-router

# Based on ubuntu
FROM ubuntu:14.04.2

MAINTAINER Nitesh Mor <mor@eecs.berkeley.edu>

# stop stupid debconf errors
ENV DEBIAN_FRONTEND noninteractive

# Update package list
RUN apt-get update

# fetch debian package
ADD gdp-router*.deb /

# install debian package, this will fail -- we will fix that in next step
RUN dpkg -i /gdp-router*.deb || true

# fix the dependencies
RUN apt-get -f install -y || true

# Make sure we can talk to it
EXPOSE 8007

USER gdp

# CMD ["/etc/init.d/gdp-router", "start"]
ENTRYPOINT ["/usr/bin/gdp-router"]
