## Docker image to run gdp-server

# Based on ubuntu
FROM ubuntu:14.04.2

MAINTAINER Nitesh Mor <mor@eecs.berkeley.edu>

# stop stupid debconf errors
ENV DEBIAN_FRONTEND noninteractive

# Update package list
RUN apt-get update

# fetch debian package
ADD gdp-server*.deb /

# install debian package, this will fail -- we will fix that in next step
RUN dpkg -i /gdp-server*.deb || true

# fix the dependencies
RUN apt-get -f install -y || true

# This uses /bin/sh's echo, that doesn't take '-e' and interprets backlash by default
RUN echo '#!/bin/bash\n/bin/sleep 120\n/usr/bin/gdplogd $*' > /wrapper.sh && chmod a+x /wrapper.sh

USER gdp

# CMD ["/etc/init.d/gdp-server", "start"]
ENTRYPOINT ["/bin/bash", "/wrapper.sh", "-D", "*=40"]
