#
#  Makefile for gdp/lang/js/apps/  (based on Makefile for gdp/)
#
#	$Id$
#
#	Copyright (c) 2014, <TBD>.  All rights reserved.
#

# Alec Dara-Abrams
# 2014-11-04
#

all:
	@echo 'Nothing to make locally here - only JavaScript programs.'
	@echo 'See the README here as well as the js/tests/ README.'
	@echo 'for details on how to run the JS programs here.'
	(cd gdpREST_server; make clean all)

clean:
	# nothing to clean locally
	(cd gdpREST_server; make clean )

run:
	@echo 'See the README here as well as the js/tests/ README.'
	@echo 'for details on how to run the JS programs here.'

tags:
	# Placeholder to remind us of the utility of tag files

