#!/bin/sh

export HOME=`echo ~gdpd`
cd $HOME

while true; do
	echo Starting gdp_router at `date`
	bin/gdp_router.py $*
	echo gdp_router exited with status $? at `date`
	sleep 5
done >> log/gdp_router 2>&1
