#!/bin/sh

if [ `whoami` = "root" ]
then
	echo "$0: cannot run as root (FATAL)"
	exit 1;
fi

export HOME=`echo ~gdp`
cd $HOME

while true; do
	echo Starting gdplogd at `date`
	bin/gdplogd $*
	echo gdplogd exited with status $? at `date`
	sleep 5
done >> log/gdplogd 2>&1
