#!/bin/sh

export HOME=`echo ~gdp`
cd $HOME

if [ ! -x bin/gdp-machine-mon ]
then
	echo "Skipping gdp-machine-mon, no executable" 1>&2
	exit 1
fi

host=`hostname -s`
gcl=${1:-"edu.berkeley.eecs.$host.gdp-machine-mon"}
echo "Logging to $gcl"
while true; do
	echo Starting gdp-machine-mon at `date`
	bin/gdp-machine-mon $gcl $*
	echo gdp-machine-mon exited with status $? at `date`
	sleep 5
done >> log/gdp-machine-mon 2>&1
