#!/bin/sh
if [ `whoami` = "root" ]
then
	echo "$0: cannot run as root (FATAL)"
	exit 1;
fi


export HOME=`echo ~gdp`
cd $HOME

while true; do
	echo Starting gdp-rest at `date`
	bin/gdp-rest $*
	echo gdp-rest exited with status $? at `date`
	sleep 5
done >> log/gdp-rest 2>&1
