#!/bin/sh 
export HOME=`echo ~gdp`
cd $HOME

if [ -x bin/run-gdp-router ]
then
	echo $0: starting gdp-router
	bin/run-gdp-router &
	sleep 4		# give router time to start & contact others
fi
if [ -x bin/run-gdplogd ]
then
	echo $0: starting gdplogd
	bin/run-gdplogd &
	sleep 4		# give logd an opportunity to advertise everything
fi
if [ -x bin/run-gdp-rest ]
then
	echo $0: starting gdp-rest
	bin/run-gdp-rest &
	sleep 1
fi
if [ -x bin/run-gdp-machine-mon ]
then
	echo $0: starting gdp-machine-mon
	bin/run-gdp-machine-mon &
fi
