/* vim: set ai sw=8 sts=8 ts=8 : */

// generic status codes
#define EP_STAT_OK		EP_STAT_NEW(EP_STAT_SEV_OK, 0, 0, 0)
#define EP_STAT_WARN		_EP_STAT_INTERNAL(WARN, EP_STAT_MOD_GENERIC, 0)
#define EP_STAT_ERROR		_EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_GENERIC, 0)
#define EP_STAT_SEVERE		_EP_STAT_INTERNAL(SEVERE, EP_STAT_MOD_GENERIC, 0)
#define EP_STAT_ABORT		_EP_STAT_INTERNAL(ABORT, EP_STAT_MOD_GENERIC, 0)

// common shared errors
#define EP_STAT_OUT_OF_MEMORY	_EP_STAT_INTERNAL(SEVERE, EP_STAT_MOD_GENERIC, 1)
#define EP_STAT_ARG_OUT_OF_RANGE _EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_GENERIC, 2)
#define EP_STAT_END_OF_FILE	_EP_STAT_INTERNAL(WARN, EP_STAT_MOD_GENERIC, 3)
#define EP_STAT_TIME_BADFORMAT	_EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_GENERIC, 4)

// cryptographic module
#define EP_STAT_CRYPTO_DIGEST	_EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_CRYPTO, 1)
#define EP_STAT_CRYPTO_SIGN	_EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_CRYPTO, 2)
#define EP_STAT_CRYPTO_VRFY	_EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_CRYPTO, 3)
#define EP_STAT_CRYPTO_BADSIG	_EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_CRYPTO, 4)
#define EP_STAT_CRYPTO_KEYTYPE	_EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_CRYPTO, 5)
#define EP_STAT_CRYPTO_KEYFORM	_EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_CRYPTO, 6)
#define EP_STAT_CRYPTO_CONVERT	_EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_CRYPTO, 7)
#define EP_STAT_CRYPTO_KEYCREAT	_EP_STAT_INTERNAL(ERROR, EP_STAT_MOD_CRYPTO, 8)
