#!/bin/sh

set -e

ETCDIR="/etc/ep_adm_params"

echo "Creating appropriate directories..."
[ -d $ETCDIR ] || mkdir $ETCDIR

if [ ! -r /etc/ep_adm_params/gdp ]; then
    mkdir -p /etc/ep_adm_params
    echo '# The list of sites to contact to find a GDP router' \
        > /etc/ep_adm_params/gdp
    echo '#    Please add local routers at the FRONT of this list' \
        >> /etc/ep_adm_params/gdp
    echo `shuf -e gdp-01.eecs.berkeley.edu \
        gdp-02.eecs.berkeley.edu \
        gdp-03.eecs.berkeley.edu ` | \
        sed -e 's/ /; /g' -e 's/^/swarm.gdp.routers=/' \
            >> /etc/ep_adm_params/gdp
fi

exit 0
