Document: gdp
Title: Debian gdp Manual
Author: <insert document author here>
Abstract: This manual describes what gdp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gdp/gdp.sgml.gz

Format: postscript
Files: /usr/share/doc/gdp/gdp.ps.gz

Format: text
Files: /usr/share/doc/gdp/gdp.text.gz

Format: HTML
Index: /usr/share/doc/gdp/html/index.html
Files: /usr/share/doc/gdp/html/*.html
