.Dd October 4, 2015
.Dt MQTT-GDP-GATEWAY 1
.Os Swarm-GDP
.Sh NAME
.Nm mqtt-gdp-gateway
.Nd copy an MQTT subscription to a log
.Sh SYNOPSIS
.Nm
.Op Fl D Ar debug-spec
.Op Fl G Ar router-ip
.Op Fl F Ar key-file
.Op Fl M Ar broker-addr
.Op Fl s
(
.Ar topic-name
.Ar log-name
) ...
.Sh DESCRIPTION
For each pair of topic and log names,
.Nm
subscribes to the indicated MQTT
.Ar topic-name
and logs all output to the named GDP
.Ar log-name .
The logs must already exist.
Each MQTT message becomes one record in the appropriate log.
.Pp
The
.Ar topic-name
is actually a pattern using standard MQTT syntax:
specifically
.Li +
matches a single lavel of hierarchy and
.Li #
matches all remaining levels of hierarchy
(it must be used as the last item in the topic pattern).
All messages published to a topic that matches the topic pattern
will be logged to the given
.Ar log-name .
.Pp
If the log has a public key included in the metadata
(see
.Xr gcl-create 8 )
then
.Nm
will try to find a corresponding secret key in the filesystem.
It searches for a file named with the internal (256 bit) name of the log
as represented in
base64url
format with a
.Sy \&.pem
file extension containing the secret key
and uses that for signing writes.
See the description of the
.Sy swarm.gdp.crypto.key.path
parameter in
.Sx ADMINISTRATIVE PARAMETERS
for details on the search path.
This search can be overridden using the
.Fl K
flag.
.Pp
Each record logged is formatted as JSON with object tags
.Li topic ,
.Li qos ,
.Li len ,
and
.Li payload .
.Pp
As a special case, if the
.Ar log-name
is a single hyphen, the records are sent to stdout rather than a log.
This is intended for debugging.
.Sh OPTIONS
.Bl -tag
.It Fl D Ar debug-spec
Turn on debugging flags using the libep-style format.
Only useful with code in hand.
.It Fl G Ar router-ip
Contact the given IP address (which may be a DNS name)
to get a connection to the GDP routing layer.
This will be replaced by automatic discovery
(for example, using Zeroconf)
soon.
The address may have an optional port number after a colon.
If this is not specified,
the names listed in the
.Va swarm.gdp.routers
runtime administrative parameter
are searched.
.It Fl K Ar key-file
Names the file containing the secret key to be used for signing.
This must be a
.Sy \&.pem
format file.
If the
.Ar key-file
is a directory,
this parameter overrides the default search path,
so the key file used is based on the name of the log.
.It Fl M Ar broker-addr
Specifies the address of the MQTT broker from which to collect the data.
.It Fl s
If set, the output does not include the wrapping metadata
(topic, qos, and len);
just the content of the payload is output.
.El
.Sh EXIT STATUS
.Bl -tag
.It 0
Success
.It 1
Some failure occurred.
.Sh ADMINISTRATIVE PARAMETERS
.Bl -tag
.It Sy swarm.gdp.crypto.key.path
Controls the search path for secret keys.
Defaults to:
.Bd -unfilled -offset indent -compact
\&.
KEYS
~/.swarm/gdp/keys
/usr/local/etc/swarm/gdp/keys
/etc/swarm/gdp/keys
.Ed
The
.Fl K
flag overrides this parameter.
.El
.\".Sh ENVIRONMENT
.\".Sh FILES
.Sh SEE ALSO
.Xr gcl-create 8
.\".Sh EXAMPLES
.Sh BUGS
Currently,
.Nm
assumes that the payload of each MQTT message
is validly formatted JSON.
This is unrealistic.
.Pp
There should be a way of specifying a separate key file for each GDP log.
.Pp
.Nm
should probably read a configuration file
to get the {topic, log, key} information.
