.Dd August 2, 2015
.Dt GCL-CREATE 8
.Os Swarm-GDP
.Sh NAME
.Nm gcl-create
.Nd create new GDP log
.Sh SYNOPSIS
.Nm gcl-create
.Op Fl D Ar debug-spec
.Op Fl e Ar key-crypto
.Op Fl G Ar router-ip
.Op Fl h Ar hash-alg
.Op Fl k Ar key-type
.Op Fl K Ar key-location
.Op Fl b Ar key-bits
.Op Fl c Ar curve-name
.Ar logd-gdp-addr
.Op Ar mdid = Ar metadata
.Op Ar external-name
.Sh DESCRIPTION
.Nm gcl-create
creates a new GDP log on a given log server.
In its default mode it also creates a public/secret keypair
associated with this log, with the public key stored in the log metadata.
Additional (text-based) metadata can be added
(arguably this should allow binary metadata as well).
Optionally the log can be given a human-understandable name;
if not specified a seemingly random name is made up.
.Ss "Metadata"
User-specified metadata may be added when a log is created.
The metadata name is stored as a 32-bit number and is generally represented
by four characters.
.Pp
In addition to user metadata,
.Nm gcl-create
adds metadata for the log creation time,
the public half of the signing key in DER format,
and the human-readable name.
.Pp
Metadata is immutable; there is no way to add, delete, or change metadata
after the log is created.
.Ss "Warning"
This implementation will change in the future,
and the command will probably be subsumed into a swarm service.
.Sh OPTIONS
.Bl -tag
.It Fl D Ar debug-spec
Turns on debugging flags using the libep-style format.
Useful only with the code in hand.
.It Fl e Ar key-crypto
Specifies symmetric encryption algorithm to use for storing the secret key.
If
.Ar key-crypto
is
.Li none
then the key is stored unencrypted on disk.
Defaults to
.Va swarm.gdp.crypto.keyenc.alg .
.It Fl G Ar router-ip
Contact the given IP address (which may be a DNS name)
to get a connection to the GDP routing layer.
This will be replaced by automatic discovery
(for example, using Zeroconf)
soon.
The address may have an optional port number after a colon.
If this is not specified,
the names listed in the
.Va swarm.gdp.routers
runtime administrative parameter
are searched.
.It Fl h Ar hash-alg
Selects the hash (message digest) algorithm used when
generating and checking signatures.
When data is appended to the log,
the log name, log metadata, record number, and record data
is hashed using this algorithm and then that hash is signed.
.It Fl k Ar key-type
Selects the type of signing key to be created for this log.
It can be one of
.Li rsa ,
.Li dsa ,
or
.Li ec .
As a special case, the type
.Li none
suppresses creation of the keypair.
.It Fl K Ar key-location
This option has two purposes.
First, if for some reason you want to create your own key
you can do so, storing the result as a PEM format keypair,
and name that file using the
.Fl K
flag.
Alternatively it can name a file in which to store the secret key,
or a directory into which the secret key will be written
named the same as the internal name of the log (with
.Va \&.pem
appended).
If
.Fl K
is not specified, the
.Va swarm.gdp.crypto.key.dir
parameter will be used as a directory name,
which defaults to
.Pa ./KEYS ,
or to the current directory if
.Pa KEYS
does not exist.
.It Fl b Ar key-bits
If the key type is RSA or DSA,
this parameter specifies the number of bits in the key.
If this is omitted and the key type is RSA,
this defaults to the value of
.Va swarm.gdp.crypto.rsa.keylen .
DSA keys use
.Va swarm.gdp.crypto.dsa.keylen .
Additionally, RSA keys use the
.Va swarm.gdp.crypto.rsa.keyexp
parameter to set the exponent.
This parameter is ignored when creating EC key pairs.
.It Fl c Ar curve-name
Sets the name of the curve to use for Elliptic Cryptography keys.
This overrides the
.Va swarm.gdp.crypto.ec.curve
parameter.
Ignored when creating RSA or DSA key pairs.
.El
.Sh EXIT STATUS
.Bl -tag
.It Li EX_CANTCREATE
It was not possible to create a secret key file.
.It Li EX_DATAERR
A command-line key file could not be parsed.
.It Li EX_NOINPUT
A command-line key file could not be opened.
.It Li EX_SOFTWARE
A successfully created public key could not be converted to external (DER) form
for storage in new log metadata.
.It Li EX_USAGE
Command line parameters are incorrect.
.It Li EX_UNAVAILABLE
A specified key length was insecure.
It was impossible to create a new key.
.El
.Sh ADMINISTRATIVE PARAMETERS
.Bl -tag
.It Va swarm.gdp.crypto.dsa.keylen
The DSA key length.
Defaults to 2048.
Overridden by
.Fl b .
.It Va swarm.gdp.crypto.ec.curve
The EC curve.
Defaults to
.Li sect283r1
(also known as
.Li B-283 ) .
Overridden by
.Fl c .
.It Va swarm.gdp.crypto.hash.alg
The hash algorithm.
Defaults to
.Li sha256 .
Overridden by
.Fl h .
.It Va swarm.gdp.crypto.key.dir
The directory in which to store secret keys.
Defaults to
.Pa KEYS
(in the current working directory).
If that subdirectory does not exist,
the keys are written to the current directory.
Overridden by
.Fl K .
.It Va swarm.gdp.crypto.keyenc.alg
The secret key (symmetric) encryption algorithm.
Defaults to
.Li aes192 .
Overridden by
.Fl e .
.It Va swarm.gdp.crypto.rsa.keyexp
The exponent to be used in the RSA algorithm.
Defaults to 3.
.It Va swarm.gdp.crypto.rsa.keylen
The key length for the RSA algorithm.
Defaults to 2048.
Overridden by
.Fl b .
.It Va swarm.gdp.crypto.sign.alg
The signing algorithm.
Defaults to
.Li ec .
Overridden by
.Fl k .
.El
.\".Sh ENVIRONMENT
.\".Sh FILES
.\".Sh SEE ALSO
.Sh EXAMPLES
.Bl -bullet
.It
To create a GCL on log server named edu.berkeley.eecs.gdp-01 using defaults:
.Dl gcl-create edu.berkeley.eecs.gdp-01 edu.berkeley.cs.eric.log01
The secret key will be written into a a file named
.Pa KEYS/<something>.pem ,
where
.Va <something>
is the base-64-encoded internal name of the log, e.g.,
.Li 1KZy5jy1QpghTe8QBmDQGqdz3a_9tVP3qp6uxlOeJdk.pem .
The password for encrypting this key will be read from the standard input.
.It
To create a log named
.Li $newlog
on the server named
.Li $logd
encrypted with a 1024-bit RSA key,
leaving the unencrypted key in a file named
.Pa mykey.pem :
.Dl gcl-create -k RSA -b 1024 -e none -K mykey.pem $logd $newlog
.It
To create a log with user-specified metadata:
.Dl gcl-create $logd Qo "MYMD=My special metadata" Qc $newlog
.It
To create a log without a human-friendly name using sha-224
as the hash (message digest) algorithm:
.Dl gcl-create -h sha224 $logd
.Nm gcl-create
will print the base-64-encoded name of the new log.
You should be careful to record that,
since it is your only way to access the log.
.El
.Sh BUGS
There should be some way to provide the key password
other than reading it from the standard input.
