#!/bin/sh

set -e

LOGDIR="/var/log/gdp"
GCLDIR="/var/swarm/gcls"
ETCDIR="/etc/ep_adm_params"

echo "Creating the 'gdp' user..."
adduser --system gdp

echo "Creating appropriate directories..."
[ -d $ETCDIR ] || mkdir $ETCDIR
[ -d $GCLDIR ] || mkdir -p $GCLDIR
[ -d $LOGDIR/ ] || mkdir $LOGDIR

# Make sure the ownerships are set up properly
# XXX: Do we need to worry about the permissions?
chown gdp:adm $LOGDIR
chown gdp:adm $GCLDIR

# Get list of routers <hardcoded for now>
echo "Figuring out router information..."
hostname=`hostname`
if echo $hostname | grep -q '^gdp-0'
then
    routers="127.0.0.1"
    for i in 01 02 03
    do
        if [ $hostname != "gdp-$i" ]
        then
            routers="$routers; gdp-$i.eecs.berkeley.edu"
        fi
    done
else
    routers="gdp-01.eecs.berkeley.edu; gdp-02.eecs.berkeley.edu; gdp-03.eecs.berkeley.edu"
fi

# Set up GDP params for, say gdp-machine-mon
echo "Setting up general GDP parameters..."
if [ ! -f $ETCDIR/gdp ]
then (
    echo "swarm.gdp.routers=$routers"
    echo "libep.time.accuracy=0.5"
    echo "libep.thr.mutex.type=errorcheck"
    echo "libep.dbg.file=stdout"
    ) > $ETCDIR/gdp
else
    echo "Warning: $ETCDIR/gdp already exists; check consistency" 2>&1
fi

# Set up things that only gdplogd will require
echo "Setting up parameters specific to gdplogd..."
if [ ! -f $ETCDIR/gdplogd ]
then (
    echo "swarm.gdplogd.gdpname=edu.berkeley.eecs.$hostname.gdplogd"
    echo "swarm.gdplogd.gcl.dir=$GCLDIR"
    ) > $ETCDIR/gdplogd
else
    echo "Warning: $ETCDIR/gdplogd already exists; check consistency" 2>&1
fi

# finally start the service
echo "Starting the service..."
service gdplogd restart
service gdp-rest restart
service gdp-machine-mon restart
