#!/bin/sh

set -e

LOGDIR="/var/log/gdp"
GCLDIR="/var/gdp/gcls"
ETCDIR="/etc/ep_adm_params"

echo "Creating the 'gdp' user..."
adduser --system gdp

echo "Creating appropriate directories..."
[ -d $ETCDIR ] || mkdir $ETCDIR
[ -d $GCLDIR ] || mkdir -p $GCLDIR
[ -d $LOGDIR ] || mkdir $LOGDIR

# Make sure the ownerships are set up properly
touch $LOGDIR/gdplogd.log 
chown -R gdp:root $LOGDIR
chown -R gdp:root $GCLDIR

# Get list of routers <hardcoded for now>
echo "Figuring out router information..."
hostname=`hostname`
routers="gdp-01.eecs.berkeley.edu; gdp-02.eecs.berkeley.edu; gdp-03.eecs.berkeley.edu"
t=`echo $routers | sed "s/; /\n/g" | shuf | tr -s '\n' ';' | sed "s/;/; /g"`
routers="127.0.0.1; $t"

# Set up GDP params for, say gdp-machine-mon
echo "Setting up general GDP parameters..."
if [ ! -f $ETCDIR/gdp ]
then (
    echo "swarm.gdp.routers=$routers"
    echo "libep.time.accuracy=0.5"
    echo "libep.thr.mutex.type=errorcheck"
    echo "libep.dbg.file=stdout"
    ) > $ETCDIR/gdp
else
    echo "Warning: $ETCDIR/gdp already exists; check consistency" 2>&1
fi

# Set up things that only gdplogd will require
echo "Setting up parameters specific to gdplogd..."
if [ ! -f $ETCDIR/gdplogd ]
then (
    echo "swarm.gdplogd.gdpname=edu.berkeley.eecs.$hostname.gdplogd"
    echo "swarm.gdplogd.gcl.dir=$GCLDIR"
    ) > $ETCDIR/gdplogd
else
    echo "Warning: $ETCDIR/gdplogd already exists; check consistency" 2>&1
fi

# finally start the service
echo "Starting the service..."
service gdplogd restart
